title: "Block Transfer"
enforce_ssl: true
description: "Blockchain Transfer Agemt"
baseurl: ""
url: "https://blocktransfer.com"
plugins:
  - jekyll-feed
include:
  - _headers
  - .well-known
  - assets
  - board-resolutions
  - clients
  - compliance
  - imgs
