title: Block Transfer
enforce_ssl: true
email: hello@blocktransfer.dev
description: "Block Transfer"
baseurl: ""
url: "blocktransfer.com"
github_username:  blocktransfer
theme: minima
plugins:
  - jekyll-feed
include:
  - .well-known
  - assets
  - board-resolutions
  - clients
  - compliance
  - imgs
  - _headers
