[ACCOUNTS]
TREASURY = "GD2OUJ4QKAPESM2NVGREBZTLFJYMLPCGSUHZVRMTQMF5T34UODVHPRCY"

[DOCUMENTATION]
BT_COMPANY_CODE = "BT"
ORG_NAME = "BlockTrans Syndicate"
ORG_DBA = "Block Transfer"
ORG_URL = "https://www.blocktransfer.com"
ORG_LOGO = "https://blocktransfer.com/logo.png"
ORG_DESCRIPTION = """
Block Transfer is spearheading innovation in the world of book-entry stock ownership. We're the bridge connecting traditional financial systems with the revolutionary potential of blockchain technology. In an era where trust and security are paramount, we're committed to providing cutting-edge solutions that empower businesses and individuals to navigate the digital economy with confidence."""
ORG_PHYSICAL_ADDRESS = "99 Wall Street #4640, New York, NY 10005" # Principal Place of Business
ORG_PHYSICAL_ADDRESS_ATTESTATION = "https://blocktransfer.com/compliance/proof-of-address.pdf"
# ORG_PHONE_NUMBER = "+10000000000"
# ORG_PHONE_NUMBER_ATTESTATION = "https://blocktransfer.com/compliance/proof-of-phone.pdf"
ORG_OFFICIAL_EMAIL = "hello@blocktransfer.dev"
ORG_SUPPORT_EMAIL = "support@blocktransfer.com"
ORG_LICENSING_AUTHORITY = "US Securities and Exchange Commission"
ORG_LICENSE_TYPE = "CIK"
ORG_LICENSE_NUMBER = "1846058"

[DOCUMENTATION.COMPLIANCE]
DESC_BUSINESS = "The Issuer offers transfer agent services."
DESC_FACILITIES = "The Issuer's employees work remotely from personal home offices."
DESC_PRODUCTS = "The Issuer primarily engages in transfer agent services."
ORG_BAL_URL = "https://issuers.info/18465058/BAL" # Latest Financial Balance Sheet
ORG_EIN = 861517229
ORG_EXCHANGE = "None"
ORG_INC_COUNTRY = "United States of America"
ORG_INC_SUBDIVISION = "Delaware"
ORG_IS_SEC_WKSI = false
ORG_IS_SHELL_COMPANY = false
ORG_OVER_10M_ASSETS = false
ORG_PREDECESSOR_NAMES = [] # ["Alias 1 (DE)", "Alias 2 (DE)", "Alias 3 Inc (WY)"]
ORG_PNL_URL = "https://issuers.info/18465058/PNL" # Latest Statement of Profit, Loss, & Retained Earnings
ORG_SIC = 6289
ORG_TRANSFER_AGENT = "self"

[DOCUMENTATION.INTERNAL]
highest_curr_solicitation = "None"
intra_state = false
min_506c_state_init_usd = 5000
registration_effective = false
reporting_company = false
req_506b_ppm = true

[[PRINCIPALS]]
name = "John Wooten"
title = "Founder"
director = true

[[LOCKOUT_PERIODS]]
start = "12-31"
end = "4-15"

[[MEETINGS]]
address = "1846058.2023*proxyvote.io"
cede_shares = "1250.00001" ###
date = "2024-3-16"
record_date = "2023-12-31"
type = "AGM"
vote_deadline = "2023-8-21T09:45:12Z"

### Do you have this or is BR MT?
# [MEETINGS.legacy_votes]
# 1 = {Y = 500, N = 455, A = 45}
# 2 = {Y = 400, N = 555, A = 45}
# 3 = {Y = 300, N = 655, A = 45}

# To the best of our knowledge, this information is up to date.