[ACCOUNTS]
TREASURY = "GD23JXCZIUUE2HLMWE4QU7G5OEHMUFWC6DGROUPO4MX2XQMZUUMFLYLR"
OFFERINGS_REG_D_506B = "Pending Form D"

[DOCUMENTATION]
BT_COMPANY_CODE = "LAYLOR"
ORG_NAME = "Laylor Corporation"
ORG_DBA = ""
ORG_URL = "https://laylorcorporation.com/"
ORG_LOGO = "https://issuers.info/imgs/1984803.png"
ORG_DESCRIPTION = """
Laylor Corporation is an innovative tech company with a strong presence in business development and technology solutions. Operating under the jurisdiction of South Carolina, Laylor Corporation's commitment to excellence is demonstrated through its comprehensive suite of services and investments in cutting-edge technologies. The company operates with the goal of driving technological advancements and promoting sustainable practices within the business landscape.

At its core, Laylor Corporation specializes in providing tailored business development services and fostering growth across diverse industries. Through strategic investments and a robust suite of resources, Laylor Corporation assists entrepreneurs in realizing their innovative visions. The company excels in areas including investment management, secure financial transactions, cryptocurrency and blockchain integration, artificial intelligence implementation, software technology, app development, and clean energy initiatives.

Laylor Corporation places a particular emphasis on supporting small and minority-owned businesses. The company's dedication to empowerment extends to individuals from various backgrounds, including those from underserved communities, women, veterans, and individuals with disabilities. By leveraging its expertise in advertising, marketing, and investment strategies, Laylor Corporation equips businesses with the tools and resources needed to expand their global reach and succeed in competitive markets.

Concerning facilities, Laylor Corporation operates with a dynamic and forward-thinking approach, leveraging a virtual business office model. Its team of professionals work remotely from individual home offices, harnessing modern technology to collaborate effectively and efficiently. This approach not only contributes to operational flexibility but also aligns with the company's commitment to sustainability and innovative work practices.

To support long-term value creation, Laylor Corporation is committed to fostering inclusive growth and technological innovation. With a strong focus on research and development, the company strives to remain at the forefront of emerging technologies, ensuring its clients benefit from the latest advancements. Its investments in clean energy initiatives and sustainable practices reflect a deep-seated commitment to environmental responsibility and a brighter future."""
ORG_PHONE_NUMBER = "+16504657193"
ORG_PHYSICAL_ADDRESS = "1318 North Main Street #1170, Summerville, SC 29483" # Principal Place of Business
ORG_SUPPORT_EMAIL = "support@laylorcorporation.com"
ORG_LICENSING_AUTHORITY = "US Securities and Exchange Commission"
ORG_LICENSE_TYPE = "CIK"
ORG_LICENSE_NUMBER = "1984803"

[DOCUMENTATION.COMPLIANCE]
DESC_BUSINESS = "The Issuer offers comprehensive technical business services, specializing in the development of innovative app platforms."
DESC_FACILITIES = "The Issuer's employees work remotely from personal home offices."
DESC_PRODUCTS = "The Issuer primarily engages in app development and consulting, providing expertise and support to diverse businesses."
ORG_BAL_URL = "https://issuers.info/1984803/BAL" # Latest Financial Balance Sheet
ORG_EIN = 861945850
ORG_IS_SEC_WKSI = false
ORG_IS_SHELL_COMPANY = false
ORG_OVER_10M_ASSETS = false
ORG_PREDECESSOR_NAMES = []
ORG_PRINCIPAL_EXECUTIVE_OFFICE = "1318 North Main Street #1170, Summerville, SC 29483"
ORG_PNL_URL = "https://issuers.info/1984803/PNL" # Latest Statement of Profit, Loss, & Retained Earnings
ORG_SIC = 7380
ORG_TRANSFER_AGENT = "BlockTrans Syndicate (99 Wall St #4640, New York, NY 10005)"

[DOCUMENTATION.INTERNAL]
blue_sky.states = []
blue_sky.exchange = "None"
highest_curr_solicitation = "None"
intra_state = false
jurisdiction.country = "US"
jurisdiction.subdivision = "SC"
min_506c_state_init_usd = 5000
registration_effective = false
reporting_company = false
req_506b_ppm = true

[[DOCUMENTATION.ORG_BLUE_SKY_REGISTRATIONS]]
state = "SC"
type = "Form D Notice"
expires = "expirationDate"

[[PRINCIPALS]]
name = "Tammy Harris"
title = "President and Chairwoman"
director = true

[[PRINCIPALS]]
name = "David Lengua"
title = "Chief Sound Officer"
director = true

[[PRINCIPALS]]
name = "Tivona Champayne"
title = "Chief Design Officer"
director = true

[[PRINCIPALS]]
name = "Alana Abner"
title = "Chief Fashion Officer"
director = true

[[PRINCIPALS]]
name = "Stacy Lee"
title = "Chief Risk Officer"
director = false

[[PRINCIPALS]]
name = "Lilly Galvez"
title = "Chief Financial Officer and Human Resource Manager"
director = false

[[PRINCIPALS]]
name = "Sheyontay Henson"
title = "None"
director = false

# To the best of our knowledge, this information is up to date.