[[CURRENCIES]]
anchor_asset_type = "stock"
approval_criteria = "Create an account at https://www.blocktransfer.com/beta/join"
approval_server = "https://api.blocktransfer.com/approvals"
authorized = 9999999999999
bankruptcy_preference = 99
code = "DEMO"
conditions = "Fully paid and non-assessable shares."
class = "D"
class_type = "common"
display_decimals = 7
dividend = "None planned."
desc = """
Example Company is used internally for product demos and development."""
dwac = "GDTCN6C4BUWRQMB7IAPXZKSBQKA22LY4I6YVBHHYCOKZCIBRRTUWCEDE"
image = "https://blocktransfer.com/imgs/1846058DEMO.png"
is_unlimited = true
is_asset_anchored = false
issuer = "GDRM3MK6KMHSYIT4E2AG2S2LWTDBJNYXE4H72C7YTTRWOWX5ZBECFWO7"
outstanding_EOFY = {2022-12-31 = 103945.94}
name = "Demo Stock"
par = "0.0001"
regulated = true
status = "test"
ticker = "DEMO"
votes_per_share = 0

[[SPLITS]]
effective = "2021-4-20"
before = 2
after = 3

[[SPLITS]]
effective = "2021-10-9"
before = 3
after = 2

[[SPLITS]]
effective = "2022-1-1"
before = 2
after = 1

# [[CURRENCIES]]
# bankruptcy_preference = 3
# code = "DEMO"
# code_template = "DEMO????????"
# class = "A"
# class_type = "common"
# convertible = ""
# cusip = ""
# dividend = "None planned."
# outstanding_EOFY = {2023-12-31 = 3248903}
# par = "0.001"
# splits_effective = "1 to 5 effective 2021-4-20|3 to 2 effective 2021-10-9|2->1 effective 2022-1-1"
# status = "test"
# votes_per_share = 1
# [[CURRENCIES]]
# authorized = 70000
# bankruptcy_preference = 2
# code = "1846058B"
# class = "B"
# class_type = "preffered"
# convertible = "1->42 convertable to Class A."
# cusip = ""
# dividend = "Expected but not obligatory 3% dividend (non-cumulative)."
# outstanding_EOFY = {2023-12-31 = 3248903}
# par = "0.001"
# rights = "Same rights as 42 shares of Class A common stock, except for the voting rights of 10 Class A shares."
# status = "test"
# votes_per_share = 10
# [[CURRENCIES]]
# authorized = 70000
# bankruptcy_preference = 3
# code = "DEMOA1"
# class = "C"
# class_type = "common"
# convertible = "1->1 convertable to class A upon exchange listing."
# cusip = ""
# dividend = "Expected but not obligatory 3% dividend (non-cumulative)."
# outstanding_EOFY = {2023-12-31 = 3248903}
# par = "0.001"
# rights = "A share of Class B preffered stock has the rights of 1500 shares of Class A common stock, except that a Class B share has the voting rights of 10 Class A shares."
# # reg_A_tier_2_yr_1_affiliated_sales_max_usd = "" -- todo: simplify reg a resales
# status = "test"
# votes_per_share = 1
# 
# [[CURRENCIES]]
# anchor_asset_type = "bond"
# bankruptcy_preference = 1
# code = "DEMOX1"
# convertible = false
# coupon_bps = 295
# cusip = ""
# maturity = "2023-10-4"
# outstanding_EOFY = {2023-12-31 = 3248903}
# par = ""
# puttable = ""
# status = "test"
