[[CURRENCIES]]
anchor_asset = "USD"
anchor_asset_type = "fiat"
approval_criteria = "Create an account at https://www.blocktransfer.com/beta/join"
approval_server = "https://api.blocktransfer.com/approvals"
attestation_of_reserve = "https://blocktransfer.com/assets/USD"
code = "BTD"
conditions = "Block Transfer is not a bank and does not itself take deposits. You will not receive any interest, credit, or other earnings on the funds in your Block Transfer account. Other conditions apply. See https://blocktransfer.com/compliance/user"
display_decimals = 7
desc = """
You can deposit US dollars as unsecured claims against BlockTrans Syndicate, a Delaware corporation regulated by the SEC. We hold deposits in fungible bulk, matched 1:1 on and off Stellar. Your funds are not insured by the FDIC or SIPC. See https://blocktransfer.com/compliance/flow-of-funds"""
image = "https://blocktransfer.com/imgs/usd.png"
is_unlimited = true
is_asset_anchored = true
issuer = "GDRM3MK6KMHSYIT4E2AG2S2LWTDBJNYXE4H72C7YTTRWOWX5ZBECFWO7"
outstanding_EOFY = {2022-12-31 = 0}
name = "BT Dollars"
redemption_instructions = "Contact support@blocktransfer.com" # "Use our app to link your bank or USDC wallet."
regulated = true
status = "live"
ticker = "USD"
